### ISSUE TITLE
Add the rate button to a fiction

### ISSUE THREAD

**Issue by Psyker** [Liinkiing/noelfic#10]
## What it is ?

The user should be able to rate a fiction

## Technical specs 

- Just add a button to rate a specific fiction

**Comment by Psyker** [comment]
Je suis en train de me demander si justement ajouter la possibilité rajouter des likes ou des claps ça fait un peu trop avec le rating déjà existant mais dont le bouton n'existe pas encore ?

Peut être le considéré comme étant un nombre de clap ou de likes justement  ?

**Comment by Liinkiing** [comment]
@Psyker ouais je pense aussi que le like ou clap fait doublon avec la note en soit. Je préfèrerai rester sur un système de note, dans le cas d'une fiction c'est plus précis et ça donne plus d'information à l'utilisateur qui veut en lire une
